### PR TITLE
Add face detection feature

### PR DESCRIPTION
**Pull request by janukobytsch**

### CODE REVIEW

**Comment by danijar** [comment]
Thanks for your update.
- Is there a reason to use `sample.original` rather than the preprocessed `sample.image`? If the detector requires it that's okay, but generally the preprocessed version should be used by extractors for performance reasons.
- The configuration options should be constructor arguments. The maximum size can be 256 then since that's the size after preprocessing and the minimum might be too large right now.
- Last, please provide short install instructions in the readme. At least add system dependencies to the readme and Python dependencies to `requirements.txt`.

I hope we can merge the feature then. Right now, it would make no sense. If you disagree with some of the points, please just comment. By the way, this time just update your branch and don't open a new pull request.

**Comment by janukobytsch** [comment]
Thanks for the feedback. Please refer to the source code comment for why the original image is used for detection. The other issues are fixed now.

**Comment by janukobytsch** [comment]
Is there any other reason why this hasn't been merged yet?

**Comment by danijar** [comment]
I've merged the feature now, but I still think we should add setup instructions the readme rather than linking a blog post.

**Pull request merged**
